In [4]:
import numpy as np
from scipy.special import comb 

In [3]:
#test array/graph from https://people.sc.fsu.edu/~jburkardt/m_src/rcm/rcm.html
graph = np.array([
            [0, 0, 1, 0, 0, 0, 0, 1, 1],
            [0, 0, 1, 0, 0, 1, 1, 1, 0],
            [1, 1, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 0, 1, 1, 0],
            [0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 1, 0, 0, 1, 1, 0, 0, 0],
            [1, 1, 0, 1, 1, 0, 0, 0, 0],
            [1, 0, 0, 1, 0, 0, 0, 0, 0]
             ])
print(graph)

[[0 0 1 0 0 0 0 1 1]
 [0 0 1 0 0 1 1 1 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 1 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 1 1 0 0 0]
 [1 1 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0]]


In [43]:
#to generate rand arr
N = 10
b = np.random.randint(2,size=(N,N))
#b_symm = np.array(np.ceil((b + b.T)/2), dtype=int)
#np.fill_diagonal(b_symm, 0)
#b_symm
print(b+b.T)

[[2 0 1 2 0 1 1 0 2 2]
 [0 2 2 1 1 2 0 0 2 0]
 [1 2 2 0 1 2 2 2 1 1]
 [2 1 0 2 0 0 2 1 2 1]
 [0 1 1 0 0 0 0 2 1 1]
 [1 2 2 0 0 0 1 0 2 1]
 [1 0 2 2 0 1 0 2 1 1]
 [0 0 2 1 2 0 2 0 1 0]
 [2 2 1 2 1 2 1 1 0 1]
 [2 0 1 1 1 1 1 0 1 2]]


In [91]:
from scipy.sparse import csr_matrix, csc_matrix
from scipy.sparse.csgraph import reverse_cuthill_mckee

In [92]:
c_g = csr_matrix(graph)
print(c_g)
perm = reverse_cuthill_mckee(c_g, True)
perm

  (0, 2)	1
  (0, 7)	1
  (0, 8)	1
  (1, 2)	1
  (1, 5)	1
  (1, 6)	1
  (1, 7)	1
  (2, 0)	1
  (2, 1)	1
  (3, 7)	1
  (3, 8)	1
  (4, 6)	1
  (4, 7)	1
  (5, 1)	1
  (5, 6)	1
  (6, 1)	1
  (6, 4)	1
  (6, 5)	1
  (7, 0)	1
  (7, 1)	1
  (7, 3)	1
  (7, 4)	1
  (8, 0)	1
  (8, 3)	1


array([4, 3, 6, 5, 7, 8, 1, 0, 2], dtype=int32)

In [93]:
g = graph[perm]
print(g)
print(c_g[perm])

[[0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1]
 [0 1 0 0 1 1 0 0 0]
 [0 1 0 0 0 0 1 0 0]
 [1 1 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 1 1 1 0]
 [0 0 1 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0]]
  (0, 7)	1
  (0, 6)	1
  (1, 8)	1
  (1, 7)	1
  (2, 5)	1
  (2, 4)	1
  (2, 1)	1
  (3, 6)	1
  (3, 1)	1
  (4, 4)	1
  (4, 3)	1
  (4, 1)	1
  (4, 0)	1
  (5, 3)	1
  (5, 0)	1
  (6, 7)	1
  (6, 6)	1
  (6, 5)	1
  (6, 2)	1
  (7, 8)	1
  (7, 7)	1
  (7, 2)	1
  (8, 1)	1
  (8, 0)	1


In [94]:
graph = [
[0, 1 , 2, 0],
[0, 0, 0, 1],
[2, 0, 0, 3],
[0, 0, 0, 0]
]
graph = csr_matrix(graph)
print(graph)


  (0, 1)	1
  (0, 2)	2
  (1, 3)	1
  (2, 0)	2
  (2, 3)	3


In [95]:
perm = reverse_cuthill_mckee(graph)
print(perm)
graph[perm].toarray()

[3 2 1 0]


array([[0, 0, 0, 0],
       [2, 0, 0, 3],
       [0, 0, 0, 1],
       [0, 1, 2, 0]], dtype=int32)

In [16]:
print(graph)
graph.shape[0]
np.array([-1]*graph.shape[0])

[[0 0 1 0 0 0 0 1 1]
 [0 0 1 0 0 1 1 1 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 1 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 1 1 0 0 0]
 [1 1 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0]]


array([-1, -1, -1, -1, -1, -1, -1, -1, -1])

### Start of Elimination Ordering.

#### Normalize Stage

In [99]:
'''Normalize Stage'''
'''preliminaries:
- node == vertex ("vertices" for plural)
- nodes' index start at 0
- all graphs and trees are represented in matrix farm
- valency is the sum of the edges' weights of a node, i.e. the sum of the row in a corresponding index, in numpy:
    np.sum(graph[node_idx])
'''
'''independent functions:'''
#clique checker:
def clique_check(graph, vertices_idx):
    #get subgraph, by slicing indexes:
    subgraph = graph[vertices_idx][:,vertices_idx]
    n = subgraph.shape[0]
    #check for clique from subgraph:
    upper_tri = subgraph[np.triu_indices(n, 1)]
    return np.sum(upper_tri) == comb(n, 2)

#subset checker:
def check_subset(graph, neighbours):
    bool_subset = False
    j_get = None
    for j_node in neighbours:
        gamma_j = np.where(graph[j_node] == 1)[0]
        j_T = np.append(gamma_j, j_node) #j^up_tack = j union gamma(j):= j added to its neighbours
        if set(neighbours).issubset(set(j_T)): #gamma(i) \subset j^up_tack
            bool_subset = True
            j_get = j_node
    return bool_subset, j_get

#more accurate way of checking the total nodes within a graph, since the edge is represented 
#by the value of A[i][j] cell, e.g if i <-> j is connected, it means A[i][j] = A[j][i] 1, otherwise 0, 
#so the size of the matrix may not correspond to the total number of nodes
def get_total_nodes(graph, row_size):
    counter = 0
    for i in range(row_size):
        if np.sum(graph[i]) > 0:
            counter += 1
    return counter

'''end'''

#normalize stage:
def normalize(graph):
    n = n_init = graph.shape[0] #number of nodes
    e = [] #placeholder node vector for elimination ordering
    w = np.array([1]*n) #weight vector for merge forest
    merge_forest = np.zeros((n,n)) #merge forest for assessment criteria
    modified = np.array([1]*n) #modified = 1, otherwise 0
    fill_count = 0

    #normalize stage
    #for now, cyclic ordering assumption: start from the 1st index to last idx, hence for-loop
    print("i, n, m, valency, valencies, e, modified")

    while np.sum(modified) > 0:
        for i in range(n):
            if np.sum(modified) == 0:
                break
            #recalculate all of the values:
            #recalculate n by excluding zero vectored rows (disconnected vertices):
            n = get_total_nodes(graph, n_init)
            valencies = np.array([np.sum(graph[j]) for j in range(n_init)]) #needs to recalculate the valency for each update due to the graph-change
            #print(i,n,m,valency,valencies,e,modified)
            mean_valency = np.sum(valencies)/n #get mean valency
            max_valency = np.max(valencies) #get max valency
            valency = np.sum(graph[i]) #get vertex's valency
            m = np.min([mean_valency, n**(1/4) + 3])
            neighbours = np.where(graph[i] == 1)[0] #get the neighbours of i
            print()
            print(i,n,m,valency,valencies,e,modified,np.sum(modified))
            #check all of the conditions based on the valency
            if valency == n-1:
                e.append(i) #add to the end
                graph[i] = graph[:,i] = 0  #remove from graph by deleting edges
                #graph = np.delete(graph, i, 0) #delete from graph -- this should be the proper deletion method, though not sure if it's faster
                #graph = np.delete(graph, i, 1)
                modified[neighbours] = 1 #set neighbours as modified
            elif (valency > n/2) and (valency == max_valency):
                e.append(i)
                graph[i] = graph[:,i] = 0
                modified[neighbours] = 1 #set neighbours as modified
            elif valency <= 1:
                e.insert(0, i) #place vertex first
                graph[i] = graph[:,i] = 0
                modified[neighbours] = 1 #set neighbours as modified
            elif valency == 2:
                e.insert(0, i)
                graph[neighbours[0]][neighbours[1]] = graph[neighbours[1]][neighbours[0]] = 1 #make edge between them -- fill the value of the cell with 1
                graph[i] = graph[:,i] = 0
                modified[neighbours] = 1 #set neighbours as modified
            elif (valency <= m) and (clique_check(graph, neighbours)):
                e.insert(0, i)
                graph[i] = graph[:,i] = 0
                modified[neighbours] = 1 #set neighbours as modified
            elif (valency <= m):
                bool_subset, j_node = check_subset(graph, neighbours) #gamma(i) \subset j^uptack, j \in gamma(i)
                if bool_subset:
                    merge_forest[j_node][i_node] = 1 #merge i into j, add directed edge j->i
                    w[j_node] += 1 #increment weight
                    graph[i] = graph[:,i] = 0
            modified[i] = 0 #set vertex as unmodified
    return e, merge_forest

In [102]:
'''graphs collection for testing'''
#test array/graph from https://people.sc.fsu.edu/~jburkardt/m_src/rcm/rcm.html
graph = np.array([
            [0, 0, 1, 0, 0, 0, 0, 1, 1],
            [0, 0, 1, 0, 0, 1, 1, 1, 0],
            [1, 1, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 0, 1, 1, 0],
            [0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 1, 0, 0, 1, 1, 0, 0, 0],
            [1, 1, 0, 1, 1, 0, 0, 0, 0],
            [1, 0, 0, 1, 0, 0, 0, 0, 0]
             ])
print(graph)

#nauru graph
graph_1 = np.zeros((24,24))
graph_1[0][1] = graph_1[0][5] = graph_1[0][21] = \
graph_1[1][3] = graph_1[1][15] = \
graph_1[2][3] = graph_1[2][4] = graph_1[2][23] = \
graph_1[3][9] = graph_1[4][5] = graph_1[4][17] = \
graph_1[5][11] = graph_1[6][7] = graph_1[6][11] = graph_1[6][19] = \
graph_1[7][9] = graph_1[7][13] = \
graph_1[8][9] = graph_1[8][10] = graph_1[8][22] = \
graph_1[10][11] = graph_1[10][16] = \
graph_1[12][13] = graph_1[12][17] = graph_1[12][18] = \
graph_1[13][15] = graph_1[14][15] = graph_1[14][16] = graph_1[14][20] = \
graph_1[16][17] = graph_1[18][19] = graph_1[18][23] = \
graph_1[19][21] = graph_1[20][21] = graph_1[20][22] = \
graph_1[22][23] = 1
graph_1 += graph_1.T
print(np.allclose(graph_1, graph_1.T, rtol=1e-05, atol=1e-08))

[[0 0 1 0 0 0 0 1 1]
 [0 0 1 0 0 1 1 1 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 1 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 1 1 0 0 0]
 [1 1 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0]]
True


In [101]:
'''testing-ground for normalize stage'''
print(normalize(graph))
print(normalize(graph_1))

#comment after testing: it kinda worked, i guess

i, n, m, valency, valencies, e, modified

0 9 2.6666666666666665 3 [3 4 2 2 2 2 3 4 2] [] [1 1 1 1 1 1 1 1 1] 9

1 9 2.6666666666666665 4 [3 4 2 2 2 2 3 4 2] [] [0 1 1 1 1 1 1 1 1] 8

2 9 2.6666666666666665 2 [3 4 2 2 2 2 3 4 2] [] [0 0 1 1 1 1 1 1 1] 7

3 8 2.75 2 [3 4 0 2 2 2 3 4 2] [2] [1 1 0 1 1 1 1 1 1] 8

4 7 2.857142857142857 2 [3 4 0 0 2 2 3 4 2] [3, 2] [1 1 0 0 1 1 1 1 1] 7

5 6 3.0 2 [3 4 0 0 0 2 3 4 2] [4, 3, 2] [1 1 0 0 0 1 1 1 1] 6

6 5 2.8 2 [3 3 0 0 0 0 2 4 2] [5, 4, 3, 2] [1 1 0 0 0 0 1 1 1] 5

7 4 2.5 3 [3 2 0 0 0 0 0 3 2] [6, 5, 4, 3, 2] [1 1 0 0 0 0 0 1 1] 4

8 3 1.3333333333333333 1 [2 1 0 0 0 0 0 0 1] [6, 5, 4, 3, 2, 7] [1 1 0 0 0 0 0 0 1] 3

0 2 1.0 1 [1 1 0 0 0 0 0 0 0] [8, 6, 5, 4, 3, 2, 7] [1 1 0 0 0 0 0 0 0] 2

1 0 nan 0 [0 0 0 0 0 0 0 0 0] [8, 6, 5, 4, 3, 2, 7, 0] [0 1 0 0 0 0 0 0 0] 1
([1, 8, 6, 5, 4, 3, 2, 7, 0], array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0.,

C:\Users\beryl\Anaconda3\lib\site-packages\ipykernel_launcher.py:65: RuntimeWarning: invalid value encountered in long_scalars


#### Separate Stage

In [54]:
'''Separate Stage'''
d_prime = 0
n_init = graph.shape[0] #should be replaced later with actual graph's nodes calculation
valencies = np.array([np.sum(graph[i]) for i in range(n_init)])
e_sep = np.argmax(valencies) #get the node with max valency
s = valencies[e_sep] #get the valency value
#need to find a set of M with max distansce from e, which requires BFS or djikstra


4


In [14]:
n_init = graph.shape[0]
print(n_init)
'''BFS'''
q = []
enque = lambda q, x: q.append(x)
deque = lambda q: q.pop(0)
visited = np.array([0]*n_init)
distances = np.array([0]*n_init)
source = root = 0
visited[source] = 1
enque(q, source)
depth = 0
q_counter = 1 #to keep track how many neighbours enqueued
while q:
    v = deque(q)
    q_counter = q_counter - 1
    if q_counter == 0:
        depth += 1
    neighbours = np.where(graph[v] == 1)[0] #enque all v's neighbours (gamma(v))
    for node_i in neighbours:
        if (visited[node_i] == 0) and (node_i not in q):
            enque(q, node_i)
            visited[node_i] = 1
            q_counter += 1
    print(v, neighbours, q, q_counter, depth)
#reverse the path:


9
0 [2 7 8] [2, 7, 8] 3 1
2 [0 1] [7, 8, 1] 3 1
7 [0 1 3 4] [8, 1, 3, 4] 4 1
8 [0 3] [1, 3, 4] 3 1
1 [2 5 6 7] [3, 4, 5, 6] 4 1
3 [7 8] [4, 5, 6] 3 1
4 [6 7] [5, 6] 2 1
5 [1 6] [6] 1 1
6 [1 4 5] [] 0 2


In [103]:
n_init = graph.shape[0]
'''dijkstra https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm''' 
#function to help djikstra algorithm:
def get_min_distance_vertex(Q, distances):
    min_dist = float("inf")
    min_v = None
    for v in range(Q.shape[0]):
        if (distances[v] < min_dist) and (Q[v] == 1):
            min_dist = distances[v]
            min_v = v
    return min_dist, min_v

#start of dijkstra algorithm:
def dijkstra_shortest_path(graph, source):
    n_init = get_total_nodes(graph, graph.shape[0])
    Q = np.array([1]*n_init)
    #print(Q)
    #source = root = 0
    distances = np.array([float("inf")]*n_init) #set distance vector
    distances[source] = 0
    prev = np.array([None]*n_init)

    while np.sum(Q) > 0:
        _, u = get_min_distance_vertex(Q, distances) #get the vertex with minimum distance
        Q[u] = False #remove u from Q
        neighbours = np.where(graph[u] == 1)[0]
        #print(u, Q, distances)
        for v in neighbours:
            if Q[v] == 1:
                alt = distances[u] + graph[u][v] #distance is equal to the weight of the edge between u and v
                if alt < distances[v]:
                    distances[v] = alt
                    prev[v] = u
                #print(alt)
    return distances

In [105]:
'''testing ground for dijkstra algo'''
dijkstra_shortest_path(graph, 8)

[1 1 1 1 1 1 1 1 1]


array([2., 0., 1., 2., 2., 1., 1., 1., 3.])

In [196]:
testgraph = np.array([[0,1,1,1],
                     [1,0,1,1],
                     [1,1,0,1],
                     [1,1,1,0]
                     ])
n = testgraph.shape[0]
upper_tri = testgraph[np.triu_indices(n, 1)]
np.sum(upper_tri) == comb(n, 2)

testgraph = np.array([[0,1,1,0],
                     [1,0,1,1],
                     [1,1,0,1],
                     [0,1,1,0]])
slice_idx = [1,2,3]
a = testgraph[slice_idx][:,slice_idx] #this is the correct one
b = testgraph[:,slice_idx]
print(a)
print(b)


[[0 1 1]
 [1 0 1]
 [1 1 0]]
[[1 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


In [43]:

def check_subset(graph, neighbours):
    bool_subset = False
    j_get = None
    for j_node in neighbours:
        gamma_j = np.where(testgraph[j_node] == 1)[0]
        j_T = np.append(gamma_j, j_node) #j^up_tack = j union gamma(j):= j added to its neighbours
        if set(neighbours).issubset(set(j_T)): #gamma(i) \subset j^up_tack
            bool_subset = True
            j_get = j_node
    return bool_subset, j_get

testgraph = np.array([[0,1,1,1],
                     [1,0,1,0],
                     [1,1,0,1],
                     [1,0,1,0]
                    ])
'''
testgraph = np.array([[0,1,0,1],
                     [1,0,1,0],
                     [0,1,0,1],
                     [1,0,1,0]
                    ])
testgraph = np.array([[0,1,1,1,1],
                      [1,0,1,0,1],
                      [1,1,0,1,0],
                      [1,0,1,0,1],
                      [1,1,0,1,0]
                     ])
'''
testforest = np.zeros((testgraph.shape))

i_node = 0
neighbours = np.where(testgraph[i_node] == 1)[0]
print(neighbours)
bool_subset, j_node = check_subset(testgraph, neighbours)
if bool_subset:
    testforest[j_node][i_node] = 1

print(testgraph)
print(testforest)

[1 2 3]
[[0 1 1 1]
 [1 0 1 0]
 [1 1 0 1]
 [1 0 1 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
